CREATE TABLE student_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL UNIQUE REFERENCES students(id),
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    token_ciphertext BYTEA NOT NULL,
    token_iv BYTEA NOT NULL,
    status VARCHAR(12) NOT NULL CHECK (status IN ('ACTIVE', 'REVOKED')),
    issued_at TIMESTAMP WITH TIME ZONE NOT NULL,
    issued_by BIGINT NOT NULL REFERENCES users(id),
    revoked_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by BIGINT NOT NULL REFERENCES users(id),
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE student_card_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id BIGINT NOT NULL REFERENCES student_cards(id),
    action VARCHAR(16) NOT NULL CHECK (action IN ('ISSUED', 'REPLACED', 'REVOKED')),
    reason VARCHAR(500),
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    actor_id BIGINT NOT NULL REFERENCES users(id)
);
CREATE INDEX idx_student_card_events_card_time ON student_card_events(card_id, occurred_at DESC);
