CREATE TABLE document_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_type VARCHAR(24) NOT NULL CHECK (document_type IN ('STUDENT_CARD', 'RECEIPT')),
    document_id BIGINT NOT NULL,
    document_version BIGINT NOT NULL,
    student_id BIGINT NOT NULL REFERENCES students(id),
    branch_id BIGINT NOT NULL REFERENCES branches(id),
    recipient_email VARCHAR(200) NOT NULL,
    idempotency_key VARCHAR(36) NOT NULL UNIQUE,
    status VARCHAR(16) NOT NULL CHECK (status IN ('QUEUED','SENDING','ACCEPTED','FAILED')),
    attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts BETWEEN 0 AND 3),
    next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL,
    provider_accepted_at TIMESTAMP WITH TIME ZONE,
    last_error VARCHAR(200),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT NOT NULL REFERENCES users(id),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by BIGINT NOT NULL REFERENCES users(id),
    version BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX idx_document_deliveries_queue ON document_deliveries(status,next_attempt_at,id);
CREATE INDEX idx_document_deliveries_student ON document_deliveries(student_id,created_at DESC);

CREATE TABLE document_delivery_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_id BIGINT NOT NULL REFERENCES document_deliveries(id),
    attempt_number INTEGER NOT NULL CHECK (attempt_number BETWEEN 1 AND 3),
    outcome VARCHAR(16) NOT NULL CHECK (outcome IN ('ACCEPTED','FAILED')),
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    detail VARCHAR(200),
    CONSTRAINT uk_delivery_attempt UNIQUE(delivery_id,attempt_number)
);
