CREATE TABLE batch_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL REFERENCES course_batches(id),
    day_of_week INTEGER NOT NULL CHECK (day_of_week BETWEEN 1 AND 7),
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    default_lecturer_user_id BIGINT REFERENCES users(id),
    classroom VARCHAR(150),
    status VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE')),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT NOT NULL REFERENCES users(id),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by BIGINT NOT NULL REFERENCES users(id),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_batch_schedules_times CHECK (start_time < end_time)
);
CREATE INDEX idx_batch_schedules_batch_status ON batch_schedules(batch_id, status);
CREATE INDEX idx_batch_schedules_lecturer ON batch_schedules(default_lecturer_user_id);

CREATE TABLE class_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL REFERENCES course_batches(id),
    session_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    lecturer_user_id BIGINT REFERENCES users(id),
    topic VARCHAR(300),
    classroom VARCHAR(150),
    status VARCHAR(20) NOT NULL CHECK (status IN ('SCHEDULED', 'COMPLETED', 'CANCELLED', 'RESCHEDULED')),
    cancellation_reason VARCHAR(2000),
    original_session_id BIGINT,
    remarks VARCHAR(2000),
    attendance_submitted_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT NOT NULL REFERENCES users(id),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by BIGINT NOT NULL REFERENCES users(id),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_class_sessions_times CHECK (start_time < end_time),
    CONSTRAINT ck_class_sessions_cancellation CHECK (status <> 'CANCELLED' OR
        (cancellation_reason IS NOT NULL AND CHAR_LENGTH(TRIM(cancellation_reason)) > 0)),
    CONSTRAINT ck_class_sessions_original CHECK (original_session_id IS NULL OR original_session_id <> id),
    CONSTRAINT uk_class_sessions_batch_id UNIQUE (batch_id, id),
    CONSTRAINT fk_class_sessions_original FOREIGN KEY (batch_id, original_session_id) REFERENCES class_sessions(batch_id, id)
);
CREATE INDEX idx_class_sessions_batch_date ON class_sessions(batch_id, session_date);
CREATE INDEX idx_class_sessions_date_status ON class_sessions(session_date, status);
CREATE INDEX idx_class_sessions_lecturer_date ON class_sessions(lecturer_user_id, session_date);
CREATE INDEX idx_class_sessions_original ON class_sessions(original_session_id);
