CREATE TABLE courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    short_code VARCHAR(20) NOT NULL,
    description TEXT,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by BIGINT NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_courses_short_code UNIQUE (short_code),
    CONSTRAINT ck_courses_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE course_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    branch_id BIGINT NOT NULL,
    batch_number VARCHAR(60) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    duration_months INTEGER NOT NULL,
    schedule_mode VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    remarks TEXT,
    registration_sequence INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by BIGINT NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_course_batches_course FOREIGN KEY (course_id) REFERENCES courses (id),
    CONSTRAINT fk_course_batches_branch FOREIGN KEY (branch_id) REFERENCES branches (id),
    CONSTRAINT uk_course_batches_batch_number UNIQUE (batch_number),
    CONSTRAINT ck_course_batches_dates CHECK (start_date <= end_date),
    CONSTRAINT ck_course_batches_duration CHECK (duration_months > 0),
    CONSTRAINT ck_course_batches_schedule_mode CHECK (schedule_mode IN ('REGULAR', 'MANUAL')),
    CONSTRAINT ck_course_batches_status CHECK (status IN ('UPCOMING', 'ACTIVE', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT ck_course_batches_registration_sequence CHECK (registration_sequence >= 0)
);

CREATE TABLE fee_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    currency_code CHAR(3) NOT NULL DEFAULT 'LKR',
    registration_fee NUMERIC(14,2) NOT NULL,
    course_fee NUMERIC(14,2) NOT NULL,
    examination_fee NUMERIC(14,2) NOT NULL,
    duration_months INTEGER NOT NULL,
    monthly_due_day INTEGER NOT NULL,
    examination_due_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by BIGINT NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_fee_plans_batch FOREIGN KEY (batch_id) REFERENCES course_batches (id),
    CONSTRAINT uk_fee_plans_batch UNIQUE (batch_id),
    CONSTRAINT ck_fee_plans_registration_fee CHECK (registration_fee >= 0),
    CONSTRAINT ck_fee_plans_course_fee CHECK (course_fee >= 0),
    CONSTRAINT ck_fee_plans_examination_fee CHECK (examination_fee >= 0),
    CONSTRAINT ck_fee_plans_duration CHECK (duration_months > 0),
    CONSTRAINT ck_fee_plans_monthly_due_day CHECK (monthly_due_day BETWEEN 1 AND 31),
    CONSTRAINT ck_fee_plans_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE batch_lecturers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    lecturer_user_id BIGINT NOT NULL,
    assignment_start_date DATE NOT NULL,
    assignment_end_date DATE,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by BIGINT NOT NULL,
    CONSTRAINT fk_batch_lecturers_batch FOREIGN KEY (batch_id) REFERENCES course_batches (id),
    CONSTRAINT fk_batch_lecturers_user FOREIGN KEY (lecturer_user_id) REFERENCES users (id),
    CONSTRAINT ck_batch_lecturers_dates CHECK (assignment_end_date IS NULL OR assignment_end_date >= assignment_start_date),
    CONSTRAINT ck_batch_lecturers_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX idx_courses_status ON courses (status);
CREATE INDEX idx_courses_name ON courses (name);
CREATE INDEX idx_course_batches_course_id ON course_batches (course_id);
CREATE INDEX idx_course_batches_branch_id ON course_batches (branch_id);
CREATE INDEX idx_course_batches_status ON course_batches (status);
CREATE INDEX idx_course_batches_start_date ON course_batches (start_date);
CREATE INDEX idx_course_batches_batch_number ON course_batches (batch_number);
CREATE INDEX idx_fee_plans_batch_id ON fee_plans (batch_id);
CREATE INDEX idx_batch_lecturers_batch_id ON batch_lecturers (batch_id);
CREATE INDEX idx_batch_lecturers_lecturer_user_id ON batch_lecturers (lecturer_user_id);
CREATE INDEX idx_batch_lecturers_status ON batch_lecturers (status);
