CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(250) NOT NULL,
    nic VARCHAR(30) NOT NULL,
    normalized_nic VARCHAR(30) NOT NULL,
    contact_number VARCHAR(30) NOT NULL,
    alternative_contact_number VARCHAR(30),
    email VARCHAR(200),
    address TEXT NOT NULL,
    date_of_birth DATE,
    gender VARCHAR(30),
    photo_storage_key VARCHAR(500),
    remarks TEXT,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by BIGINT NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_students_normalized_nic UNIQUE (normalized_nic),
    CONSTRAINT ck_students_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT fk_students_created_by FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT fk_students_updated_by FOREIGN KEY (updated_by) REFERENCES users (id)
);

CREATE INDEX idx_students_full_name ON students (full_name);
CREATE INDEX idx_students_contact_number ON students (contact_number);
CREATE INDEX idx_students_status ON students (status);
