CREATE TABLE enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES students(id),
    batch_id BIGINT NOT NULL REFERENCES course_batches(id),
    registration_number VARCHAR(100) NOT NULL,
    sequence_number INTEGER NOT NULL CHECK (sequence_number BETWEEN 1 AND 9999),
    enrollment_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE', 'COMPLETED', 'WITHDRAWN', 'SUSPENDED', 'CANCELLED')),
    remarks TEXT,
    currency_code VARCHAR(3) NOT NULL,
    registration_fee NUMERIC(14,2) NOT NULL CHECK (registration_fee >= 0),
    course_fee NUMERIC(14,2) NOT NULL CHECK (course_fee >= 0),
    examination_fee NUMERIC(14,2) NOT NULL CHECK (examination_fee >= 0),
    duration_months INTEGER NOT NULL CHECK (duration_months > 0),
    monthly_due_day INTEGER NOT NULL CHECK (monthly_due_day BETWEEN 1 AND 31),
    examination_due_date DATE NOT NULL,
    batch_start_date DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT NOT NULL REFERENCES users(id),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by BIGINT NOT NULL REFERENCES users(id),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_enrollments_student_batch UNIQUE (student_id, batch_id),
    CONSTRAINT uk_enrollments_registration UNIQUE (registration_number),
    CONSTRAINT uk_enrollments_batch_sequence UNIQUE (batch_id, sequence_number)
);
CREATE INDEX idx_enrollments_batch_status ON enrollments(batch_id, status);
CREATE INDEX idx_enrollments_student ON enrollments(student_id);

CREATE TABLE student_charges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id BIGINT NOT NULL REFERENCES enrollments(id),
    charge_type VARCHAR(30) NOT NULL CHECK (charge_type IN ('REGISTRATION_FEE', 'COURSE_INSTALLMENT', 'EXAMINATION_FEE', 'OTHER')),
    installment_number INTEGER NOT NULL DEFAULT 0,
    description VARCHAR(300) NOT NULL,
    due_date DATE NOT NULL,
    original_amount NUMERIC(14,2) NOT NULL CHECK (original_amount >= 0),
    discount_amount NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    waiver_amount NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (waiver_amount >= 0),
    final_payable_amount NUMERIC(14,2) NOT NULL CHECK (final_payable_amount >= 0),
    currency_code VARCHAR(3) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('UPCOMING', 'DUE', 'OVERDUE', 'PAID', 'WAIVED', 'CANCELLED')),
    paid_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT NOT NULL REFERENCES users(id),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by BIGINT NOT NULL REFERENCES users(id),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_student_charges_installment UNIQUE (enrollment_id, charge_type, installment_number),
    CONSTRAINT ck_student_charges_amount CHECK (final_payable_amount = original_amount - discount_amount - waiver_amount),
    CONSTRAINT ck_student_charges_installment CHECK (
        (charge_type = 'COURSE_INSTALLMENT' AND installment_number > 0)
        OR (charge_type <> 'COURSE_INSTALLMENT' AND installment_number = 0))
);
CREATE INDEX idx_student_charges_enrollment_due ON student_charges(enrollment_id, due_date);
CREATE INDEX idx_student_charges_status_due ON student_charges(status, due_date);
